### ISSUE TITLE
Node.js is a run time environment of javascript not a web framework like express.js or django

### ISSUE THREAD

**Issue by Ashish1323** [jonerer/semla#8]
![8](https://user-images.githubusercontent.com/42762022/93816001-85d5ab00-fc74-11ea-8105-ea082dae9919.JPG)

**Comment by jonerer** [comment]
Thanks for the interest! I mean Semla is a node.js based web framework :) Sorry the documentation is quite lacking so far

**Comment by Ashish1323** [comment]
Oops, I thought the same!
